INSERT INTO `commercial_pays` VALUES (1,'ac','Ascension île');
INSERT INTO `commercial_pays` VALUES (2,'ad','Andorre');
INSERT INTO `commercial_pays` VALUES (3,'ae','Emirats Arabes Unis');
INSERT INTO `commercial_pays` VALUES (4,'af','Afghanistan');
INSERT INTO `commercial_pays` VALUES (5,'ag','Antigua et Barbuda');
INSERT INTO `commercial_pays` VALUES (6,'ai','Anguilla');
INSERT INTO `commercial_pays` VALUES (7,'al','Albanie');
INSERT INTO `commercial_pays` VALUES (8,'am','Arménie');
INSERT INTO `commercial_pays` VALUES (9,'an','Antilles Neerlandaises');
INSERT INTO `commercial_pays` VALUES (10,'ao','Angola');
INSERT INTO `commercial_pays` VALUES (11,'aq','Antarctique');
INSERT INTO `commercial_pays` VALUES (12,'ar','Argentine');
INSERT INTO `commercial_pays` VALUES (13,'as','American Samoa');
INSERT INTO `commercial_pays` VALUES (14,'at','Autriche');
INSERT INTO `commercial_pays` VALUES (15,'au','Australie');
INSERT INTO `commercial_pays` VALUES (16,'aw','Aruba');
INSERT INTO `commercial_pays` VALUES (17,'az','Azerbaidjan');
INSERT INTO `commercial_pays` VALUES (18,'ba','Bosnie Herzégovine');
INSERT INTO `commercial_pays` VALUES (19,'bb','Barbade');
INSERT INTO `commercial_pays` VALUES (20,'bd','Bangladesh');
INSERT INTO `commercial_pays` VALUES (21,'be','Belgique');
INSERT INTO `commercial_pays` VALUES (22,'bf','Burkina Faso');
INSERT INTO `commercial_pays` VALUES (23,'bg','Bulgarie');
INSERT INTO `commercial_pays` VALUES (24,'bh','Bahrein');
INSERT INTO `commercial_pays` VALUES (25,'bi','Burundi');
INSERT INTO `commercial_pays` VALUES (26,'bj','Bénin');
INSERT INTO `commercial_pays` VALUES (27,'bm','Bermudes');
INSERT INTO `commercial_pays` VALUES (28,'bn','Brunei');
INSERT INTO `commercial_pays` VALUES (29,'bo','Bolivie');
INSERT INTO `commercial_pays` VALUES (30,'br','Brésil');
INSERT INTO `commercial_pays` VALUES (31,'bs','Bahamas');
INSERT INTO `commercial_pays` VALUES (32,'bt','Bhoutan');
INSERT INTO `commercial_pays` VALUES (33,'bv','Bouvet île');
INSERT INTO `commercial_pays` VALUES (34,'bw','Botswana');
INSERT INTO `commercial_pays` VALUES (35,'by','Biélorussie');
INSERT INTO `commercial_pays` VALUES (36,'bz','Bélize');
INSERT INTO `commercial_pays` VALUES (37,'ca','Canada');
INSERT INTO `commercial_pays` VALUES (38,'cc','Cocos Keeling); îles');
INSERT INTO `commercial_pays` VALUES (39,'cd','Rép. du Congo');
INSERT INTO `commercial_pays` VALUES (40,'cf','Rép Centrafricaine');
INSERT INTO `commercial_pays` VALUES (41,'ch','Suisse');
INSERT INTO `commercial_pays` VALUES (42,'ci','Côte d''Ivoire');
INSERT INTO `commercial_pays` VALUES (43,'ck','Cook îles');
INSERT INTO `commercial_pays` VALUES (44,'cl','Chili');
INSERT INTO `commercial_pays` VALUES (45,'cm','Cameroun');
INSERT INTO `commercial_pays` VALUES (46,'cn','Chine');
INSERT INTO `commercial_pays` VALUES (47,'co','Colombie');
INSERT INTO `commercial_pays` VALUES (48,'cr','Costa Rica');
INSERT INTO `commercial_pays` VALUES (49,'cs','Serbie Montenegro');
INSERT INTO `commercial_pays` VALUES (50,'cu','Cuba');
INSERT INTO `commercial_pays` VALUES (51,'cv','Cap Vert');
INSERT INTO `commercial_pays` VALUES (52,'cx','Christmas île');
INSERT INTO `commercial_pays` VALUES (53,'cy','Chypre');
INSERT INTO `commercial_pays` VALUES (54,'cz','Tchéquie');
INSERT INTO `commercial_pays` VALUES (55,'de','Allemagne');
INSERT INTO `commercial_pays` VALUES (56,'dj','Djibouti');
INSERT INTO `commercial_pays` VALUES (57,'dk','Danemark');
INSERT INTO `commercial_pays` VALUES (58,'dm','Dominique');
INSERT INTO `commercial_pays` VALUES (59,'do','Rép Dominicaine');
INSERT INTO `commercial_pays` VALUES (60,'dz','Algérie');
INSERT INTO `commercial_pays` VALUES (61,'ec','Equateur');
INSERT INTO `commercial_pays` VALUES (62,'ee','Estonie');
INSERT INTO `commercial_pays` VALUES (63,'eg','Egypte');
INSERT INTO `commercial_pays` VALUES (64,'eh','Sahara Occidental');
INSERT INTO `commercial_pays` VALUES (65,'er','Erythrée');
INSERT INTO `commercial_pays` VALUES (66,'es','Espagne');
INSERT INTO `commercial_pays` VALUES (67,'et','Ethiopie');
INSERT INTO `commercial_pays` VALUES (68,'fi','Finlande');
INSERT INTO `commercial_pays` VALUES (69,'fj','Fidji');
INSERT INTO `commercial_pays` VALUES (70,'fk','Falkland Malouines); îles');
INSERT INTO `commercial_pays` VALUES (71,'fm','Micronésie');
INSERT INTO `commercial_pays` VALUES (72,'fo','Faroe îles');
INSERT INTO `commercial_pays` VALUES (73,'fr','France');
INSERT INTO `commercial_pays` VALUES (74,'ga','Gabon');
INSERT INTO `commercial_pays` VALUES (75,'gb','Grande Bretagne');
INSERT INTO `commercial_pays` VALUES (76,'gd','Grenade');
INSERT INTO `commercial_pays` VALUES (77,'ge','Géorgie');
INSERT INTO `commercial_pays` VALUES (78,'gf','Guyane Française');
INSERT INTO `commercial_pays` VALUES (79,'gg','Guernsey');
INSERT INTO `commercial_pays` VALUES (80,'gh','Ghana');
INSERT INTO `commercial_pays` VALUES (81,'gi','Gibraltar');
INSERT INTO `commercial_pays` VALUES (82,'gl','Groenland');
INSERT INTO `commercial_pays` VALUES (83,'gm','Gambie');
INSERT INTO `commercial_pays` VALUES (84,'gn','Guinée');
INSERT INTO `commercial_pays` VALUES (85,'gp','Guadeloupe');
INSERT INTO `commercial_pays` VALUES (86,'gq','Guinée Equatoriale');
INSERT INTO `commercial_pays` VALUES (87,'gr','Grèce');
INSERT INTO `commercial_pays` VALUES (88,'gs','Géorgie du sud');
INSERT INTO `commercial_pays` VALUES (89,'gt','Guatemala');
INSERT INTO `commercial_pays` VALUES (90,'gu','Guam');
INSERT INTO `commercial_pays` VALUES (91,'gw','Guinée-Bissau');
INSERT INTO `commercial_pays` VALUES (92,'gy','Guyana');
INSERT INTO `commercial_pays` VALUES (93,'hk','Hong Kong');
INSERT INTO `commercial_pays` VALUES (94,'hm','Heard et McDonald îles');
INSERT INTO `commercial_pays` VALUES (95,'hn','Honduras');
INSERT INTO `commercial_pays` VALUES (96,'hr','Croatie');
INSERT INTO `commercial_pays` VALUES (97,'ht','Haiti');
INSERT INTO `commercial_pays` VALUES (98,'hu','Hongrie');
INSERT INTO `commercial_pays` VALUES (99,'id','Indonésie');
INSERT INTO `commercial_pays` VALUES (100,'ie','Irlande');
INSERT INTO `commercial_pays` VALUES (101,'il','Israël');
INSERT INTO `commercial_pays` VALUES (102,'im','Ile de Man');
INSERT INTO `commercial_pays` VALUES (103,'in','Inde');
INSERT INTO `commercial_pays` VALUES (104,'io','Ter. Brit. Océan Indien');
INSERT INTO `commercial_pays` VALUES (105,'iq','Iraq');
INSERT INTO `commercial_pays` VALUES (106,'ir','Iran');
INSERT INTO `commercial_pays` VALUES (107,'is','Islande');
INSERT INTO `commercial_pays` VALUES (108,'it','Italie');
INSERT INTO `commercial_pays` VALUES (109,'je','Jersey');
INSERT INTO `commercial_pays` VALUES (110,'jm','Jamaïque');
INSERT INTO `commercial_pays` VALUES (111,'jo','Jordanie');
INSERT INTO `commercial_pays` VALUES (112,'jp','Japon');
INSERT INTO `commercial_pays` VALUES (113,'ke','Kenya');
INSERT INTO `commercial_pays` VALUES (114,'kg','Kirghizistan');
INSERT INTO `commercial_pays` VALUES (115,'kh','Cambodge');
INSERT INTO `commercial_pays` VALUES (116,'ki','Kiribati');
INSERT INTO `commercial_pays` VALUES (117,'km','Comores');
INSERT INTO `commercial_pays` VALUES (118,'kn','Saint Kitts et Nevis');
INSERT INTO `commercial_pays` VALUES (119,'kp','Corée du nord');
INSERT INTO `commercial_pays` VALUES (120,'kr','Corée du sud');
INSERT INTO `commercial_pays` VALUES (121,'kw','Koweït');
INSERT INTO `commercial_pays` VALUES (122,'ky','Caïmanes îles');
INSERT INTO `commercial_pays` VALUES (123,'kz','Kazakhstan');
INSERT INTO `commercial_pays` VALUES (124,'la','Laos');
INSERT INTO `commercial_pays` VALUES (125,'lb','Liban');
INSERT INTO `commercial_pays` VALUES (126,'lc','Sainte Lucie');
INSERT INTO `commercial_pays` VALUES (127,'li','Liechtenstein');
INSERT INTO `commercial_pays` VALUES (128,'lk','Sri Lanka');
INSERT INTO `commercial_pays` VALUES (129,'lr','Liberia');
INSERT INTO `commercial_pays` VALUES (130,'ls','Lesotho');
INSERT INTO `commercial_pays` VALUES (131,'lt','Lituanie');
INSERT INTO `commercial_pays` VALUES (132,'lu','Luxembourg');
INSERT INTO `commercial_pays` VALUES (133,'lv','Lettonie');
INSERT INTO `commercial_pays` VALUES (134,'ly','Libye');
INSERT INTO `commercial_pays` VALUES (135,'ma','Maroc');
INSERT INTO `commercial_pays` VALUES (136,'mc','Monaco');
INSERT INTO `commercial_pays` VALUES (137,'md','Moldavie');
INSERT INTO `commercial_pays` VALUES (138,'mg','Madagascar');
INSERT INTO `commercial_pays` VALUES (139,'mh','Marshall îles');
INSERT INTO `commercial_pays` VALUES (140,'mk','Macédoine');
INSERT INTO `commercial_pays` VALUES (141,'ml','Mali');
INSERT INTO `commercial_pays` VALUES (142,'mm','Myanmar');
INSERT INTO `commercial_pays` VALUES (143,'mn','Mongolie');
INSERT INTO `commercial_pays` VALUES (144,'mo','Macao');
INSERT INTO `commercial_pays` VALUES (145,'mp','Mariannes du nord îles');
INSERT INTO `commercial_pays` VALUES (146,'mq','Martinique');
INSERT INTO `commercial_pays` VALUES (147,'mr','Mauritanie');
INSERT INTO `commercial_pays` VALUES (148,'ms','Montserrat');
INSERT INTO `commercial_pays` VALUES (149,'mt','Malte');
INSERT INTO `commercial_pays` VALUES (150,'mu','Maurice île');
INSERT INTO `commercial_pays` VALUES (151,'mv','Maldives');
INSERT INTO `commercial_pays` VALUES (152,'mw','Malawi');
INSERT INTO `commercial_pays` VALUES (153,'mx','Mexique');
INSERT INTO `commercial_pays` VALUES (154,'my','Malaisie');
INSERT INTO `commercial_pays` VALUES (155,'mz','Mozambique');
INSERT INTO `commercial_pays` VALUES (156,'na','Namibie');
INSERT INTO `commercial_pays` VALUES (157,'nc','Nouvelle Calédonie');
INSERT INTO `commercial_pays` VALUES (158,'ne','Niger');
INSERT INTO `commercial_pays` VALUES (159,'nf','Norfolk île');
INSERT INTO `commercial_pays` VALUES (160,'ng','Nigéria');
INSERT INTO `commercial_pays` VALUES (161,'ni','Nicaragua');
INSERT INTO `commercial_pays` VALUES (162,'nl','Pays Bas');
INSERT INTO `commercial_pays` VALUES (163,'no','Norvège');
INSERT INTO `commercial_pays` VALUES (164,'np','Népal');
INSERT INTO `commercial_pays` VALUES (165,'nr','Nauru');
INSERT INTO `commercial_pays` VALUES (166,'nu','Niue');
INSERT INTO `commercial_pays` VALUES (167,'nz','Nouvelle Zélande');
INSERT INTO `commercial_pays` VALUES (168,'om','Oman');
INSERT INTO `commercial_pays` VALUES (169,'pa','Panama');
INSERT INTO `commercial_pays` VALUES (170,'pe','Pérou');
INSERT INTO `commercial_pays` VALUES (171,'pf','Polynésie Française');
INSERT INTO `commercial_pays` VALUES (172,'pg','Papouasie Nvelle Guinée');
INSERT INTO `commercial_pays` VALUES (173,'ph','Philippines');
INSERT INTO `commercial_pays` VALUES (174,'pk','Pakistan');
INSERT INTO `commercial_pays` VALUES (175,'pl','Pologne');
INSERT INTO `commercial_pays` VALUES (176,'pm','St. Pierre et Miquelon');
INSERT INTO `commercial_pays` VALUES (177,'pn','Pitcairn île');
INSERT INTO `commercial_pays` VALUES (178,'pr','Porto Rico');
INSERT INTO `commercial_pays` VALUES (179,'pt','Portugal');
INSERT INTO `commercial_pays` VALUES (180,'pw','Palau');
INSERT INTO `commercial_pays` VALUES (181,'py','Paraguay');
INSERT INTO `commercial_pays` VALUES (182,'qa','Qatar');
INSERT INTO `commercial_pays` VALUES (183,'re','Réunion île de la');
INSERT INTO `commercial_pays` VALUES (184,'ro','Roumanie');
INSERT INTO `commercial_pays` VALUES (185,'ru','Russie');
INSERT INTO `commercial_pays` VALUES (186,'rw','Rwanda');
INSERT INTO `commercial_pays` VALUES (187,'sa','Arabie Saoudite');
INSERT INTO `commercial_pays` VALUES (188,'sb','Salomon îles');
INSERT INTO `commercial_pays` VALUES (189,'sc','Seychelles');
INSERT INTO `commercial_pays` VALUES (190,'sd','Soudan');
INSERT INTO `commercial_pays` VALUES (191,'se','Suède');
INSERT INTO `commercial_pays` VALUES (192,'sg','Singapour');
INSERT INTO `commercial_pays` VALUES (193,'sh','St. Hélène');
INSERT INTO `commercial_pays` VALUES (194,'si','Slovénie');
INSERT INTO `commercial_pays` VALUES (195,'sj','Svalbard/Jan Mayen îles');
INSERT INTO `commercial_pays` VALUES (196,'sk','Slovaquie');
INSERT INTO `commercial_pays` VALUES (197,'sl','Sierra Leone');
INSERT INTO `commercial_pays` VALUES (198,'sm','Saint-Marin');
INSERT INTO `commercial_pays` VALUES (199,'sn','Sénégal');
INSERT INTO `commercial_pays` VALUES (200,'so','Somalie');
INSERT INTO `commercial_pays` VALUES (201,'sr','Suriname');
INSERT INTO `commercial_pays` VALUES (202,'st','Sao Tome et Principe');
INSERT INTO `commercial_pays` VALUES (203,'su','Ex U.R.S.S.');
INSERT INTO `commercial_pays` VALUES (204,'sv','Salvador');
INSERT INTO `commercial_pays` VALUES (205,'sy','Syrie');
INSERT INTO `commercial_pays` VALUES (206,'sz','Swaziland');
INSERT INTO `commercial_pays` VALUES (207,'tc','Turks et Caïques îles');
INSERT INTO `commercial_pays` VALUES (208,'td','Tchad');
INSERT INTO `commercial_pays` VALUES (209,'tf','Territoires Fr du sud');
INSERT INTO `commercial_pays` VALUES (210,'tg','Togo');
INSERT INTO `commercial_pays` VALUES (211,'th','Thailande');
INSERT INTO `commercial_pays` VALUES (212,'tj','Tadjikistan');
INSERT INTO `commercial_pays` VALUES (213,'tk','Tokelau');
INSERT INTO `commercial_pays` VALUES (214,'tm','Turkménistan');
INSERT INTO `commercial_pays` VALUES (215,'tn','Tunisie');
INSERT INTO `commercial_pays` VALUES (216,'to','Tonga');
INSERT INTO `commercial_pays` VALUES (217,'tp','Timor Oriental');
INSERT INTO `commercial_pays` VALUES (218,'tr','Turquie');
INSERT INTO `commercial_pays` VALUES (219,'tt','Trinité et Tobago');
INSERT INTO `commercial_pays` VALUES (220,'tv','Tuvalu');
INSERT INTO `commercial_pays` VALUES (221,'tw','Taiwan');
INSERT INTO `commercial_pays` VALUES (222,'tz','Tanzanie');
INSERT INTO `commercial_pays` VALUES (223,'ua','Ukraine');
INSERT INTO `commercial_pays` VALUES (224,'ug','Ouganda');
INSERT INTO `commercial_pays` VALUES (225,'uk','Royaume Uni');
INSERT INTO `commercial_pays` VALUES (226,'um','US Minor Outlying îles');
INSERT INTO `commercial_pays` VALUES (227,'us','Etats-Unis');
INSERT INTO `commercial_pays` VALUES (228,'uy','Uruguay');
INSERT INTO `commercial_pays` VALUES (229,'uz','Ouzbékistan');
INSERT INTO `commercial_pays` VALUES (230,'va','Vatican');
INSERT INTO `commercial_pays` VALUES (231,'vc','St Vincent et les Grenadines');
INSERT INTO `commercial_pays` VALUES (232,'ve','Venezuela');
INSERT INTO `commercial_pays` VALUES (233,'vg','Vierges Brit. îles');
INSERT INTO `commercial_pays` VALUES (234,'vi','Vierges USA îles');
INSERT INTO `commercial_pays` VALUES (235,'vn','Viêt Nam');
INSERT INTO `commercial_pays` VALUES (236,'vu','Vanuatu');
INSERT INTO `commercial_pays` VALUES (237,'wf','Wallis et Futuna îles');
INSERT INTO `commercial_pays` VALUES (238,'ws','Western Samoa');
INSERT INTO `commercial_pays` VALUES (239,'ye','Yemen');
INSERT INTO `commercial_pays` VALUES (240,'yt','Mayotte');
INSERT INTO `commercial_pays` VALUES (241,'yu','Yugoslavie');
INSERT INTO `commercial_pays` VALUES (242,'za','Afrique du Sud');
INSERT INTO `commercial_pays` VALUES (243,'zm','Zambie');
INSERT INTO `commercial_pays` VALUES (244,'zr','Rép. Dém. du Congo ex Zaïre');
INSERT INTO `commercial_pays` VALUES (245,'zw','Zimbabwe');
